# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /src/app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /src/app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /src/app/CMakeFiles /src/app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /src/app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wnc-app

# Build rule for target.
wnc-app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wnc-app
.PHONY : wnc-app

# fast build rule for target.
wnc-app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/build
.PHONY : wnc-app/fast

src/ba.o: src/ba.cpp.o
.PHONY : src/ba.o

# target to build an object file
src/ba.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/ba.cpp.o
.PHONY : src/ba.cpp.o

src/ba.i: src/ba.cpp.i
.PHONY : src/ba.i

# target to preprocess a source file
src/ba.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/ba.cpp.i
.PHONY : src/ba.cpp.i

src/ba.s: src/ba.cpp.s
.PHONY : src/ba.s

# target to generate assembly for a file
src/ba.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/ba.cpp.s
.PHONY : src/ba.cpp.s

src/bounding_box.o: src/bounding_box.cpp.o
.PHONY : src/bounding_box.o

# target to build an object file
src/bounding_box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/bounding_box.cpp.o
.PHONY : src/bounding_box.cpp.o

src/bounding_box.i: src/bounding_box.cpp.i
.PHONY : src/bounding_box.i

# target to preprocess a source file
src/bounding_box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/bounding_box.cpp.i
.PHONY : src/bounding_box.cpp.i

src/bounding_box.s: src/bounding_box.cpp.s
.PHONY : src/bounding_box.s

# target to generate assembly for a file
src/bounding_box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/bounding_box.cpp.s
.PHONY : src/bounding_box.cpp.s

src/config_reader.o: src/config_reader.cpp.o
.PHONY : src/config_reader.o

# target to build an object file
src/config_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/config_reader.cpp.o
.PHONY : src/config_reader.cpp.o

src/config_reader.i: src/config_reader.cpp.i
.PHONY : src/config_reader.i

# target to preprocess a source file
src/config_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/config_reader.cpp.i
.PHONY : src/config_reader.cpp.i

src/config_reader.s: src/config_reader.cpp.s
.PHONY : src/config_reader.s

# target to generate assembly for a file
src/config_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/config_reader.cpp.s
.PHONY : src/config_reader.cpp.s

src/correlation_kernel.o: src/correlation_kernel.cpp.o
.PHONY : src/correlation_kernel.o

# target to build an object file
src/correlation_kernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/correlation_kernel.cpp.o
.PHONY : src/correlation_kernel.cpp.o

src/correlation_kernel.i: src/correlation_kernel.cpp.i
.PHONY : src/correlation_kernel.i

# target to preprocess a source file
src/correlation_kernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/correlation_kernel.cpp.i
.PHONY : src/correlation_kernel.cpp.i

src/correlation_kernel.s: src/correlation_kernel.cpp.s
.PHONY : src/correlation_kernel.s

# target to generate assembly for a file
src/correlation_kernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/correlation_kernel.cpp.s
.PHONY : src/correlation_kernel.cpp.s

src/dla_config.o: src/dla_config.cpp.o
.PHONY : src/dla_config.o

# target to build an object file
src/dla_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dla_config.cpp.o
.PHONY : src/dla_config.cpp.o

src/dla_config.i: src/dla_config.cpp.i
.PHONY : src/dla_config.i

# target to preprocess a source file
src/dla_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dla_config.cpp.i
.PHONY : src/dla_config.cpp.i

src/dla_config.s: src/dla_config.cpp.s
.PHONY : src/dla_config.s

# target to generate assembly for a file
src/dla_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dla_config.cpp.s
.PHONY : src/dla_config.cpp.s

src/dpvo.o: src/dpvo.cpp.o
.PHONY : src/dpvo.o

# target to build an object file
src/dpvo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dpvo.cpp.o
.PHONY : src/dpvo.cpp.o

src/dpvo.i: src/dpvo.cpp.i
.PHONY : src/dpvo.i

# target to preprocess a source file
src/dpvo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dpvo.cpp.i
.PHONY : src/dpvo.cpp.i

src/dpvo.s: src/dpvo.cpp.s
.PHONY : src/dpvo.s

# target to generate assembly for a file
src/dpvo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dpvo.cpp.s
.PHONY : src/dpvo.cpp.s

src/dpvo_viewer.o: src/dpvo_viewer.cpp.o
.PHONY : src/dpvo_viewer.o

# target to build an object file
src/dpvo_viewer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dpvo_viewer.cpp.o
.PHONY : src/dpvo_viewer.cpp.o

src/dpvo_viewer.i: src/dpvo_viewer.cpp.i
.PHONY : src/dpvo_viewer.i

# target to preprocess a source file
src/dpvo_viewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dpvo_viewer.cpp.i
.PHONY : src/dpvo_viewer.cpp.i

src/dpvo_viewer.s: src/dpvo_viewer.cpp.s
.PHONY : src/dpvo_viewer.s

# target to generate assembly for a file
src/dpvo_viewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/dpvo_viewer.cpp.s
.PHONY : src/dpvo_viewer.cpp.s

src/fnet.o: src/fnet.cpp.o
.PHONY : src/fnet.o

# target to build an object file
src/fnet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/fnet.cpp.o
.PHONY : src/fnet.cpp.o

src/fnet.i: src/fnet.cpp.i
.PHONY : src/fnet.i

# target to preprocess a source file
src/fnet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/fnet.cpp.i
.PHONY : src/fnet.cpp.i

src/fnet.s: src/fnet.cpp.s
.PHONY : src/fnet.s

# target to generate assembly for a file
src/fnet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/fnet.cpp.s
.PHONY : src/fnet.cpp.s

src/fnet_onnx.o: src/fnet_onnx.cpp.o
.PHONY : src/fnet_onnx.o

# target to build an object file
src/fnet_onnx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/fnet_onnx.cpp.o
.PHONY : src/fnet_onnx.cpp.o

src/fnet_onnx.i: src/fnet_onnx.cpp.i
.PHONY : src/fnet_onnx.i

# target to preprocess a source file
src/fnet_onnx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/fnet_onnx.cpp.i
.PHONY : src/fnet_onnx.cpp.i

src/fnet_onnx.s: src/fnet_onnx.cpp.s
.PHONY : src/fnet_onnx.s

# target to generate assembly for a file
src/fnet_onnx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/fnet_onnx.cpp.s
.PHONY : src/fnet_onnx.cpp.s

src/img_util.o: src/img_util.cpp.o
.PHONY : src/img_util.o

# target to build an object file
src/img_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/img_util.cpp.o
.PHONY : src/img_util.cpp.o

src/img_util.i: src/img_util.cpp.i
.PHONY : src/img_util.i

# target to preprocess a source file
src/img_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/img_util.cpp.i
.PHONY : src/img_util.cpp.i

src/img_util.s: src/img_util.cpp.s
.PHONY : src/img_util.s

# target to generate assembly for a file
src/img_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/img_util.cpp.s
.PHONY : src/img_util.cpp.s

src/inet.o: src/inet.cpp.o
.PHONY : src/inet.o

# target to build an object file
src/inet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/inet.cpp.o
.PHONY : src/inet.cpp.o

src/inet.i: src/inet.cpp.i
.PHONY : src/inet.i

# target to preprocess a source file
src/inet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/inet.cpp.i
.PHONY : src/inet.cpp.i

src/inet.s: src/inet.cpp.s
.PHONY : src/inet.s

# target to generate assembly for a file
src/inet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/inet.cpp.s
.PHONY : src/inet.cpp.s

src/inet_onnx.o: src/inet_onnx.cpp.o
.PHONY : src/inet_onnx.o

# target to build an object file
src/inet_onnx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/inet_onnx.cpp.o
.PHONY : src/inet_onnx.cpp.o

src/inet_onnx.i: src/inet_onnx.cpp.i
.PHONY : src/inet_onnx.i

# target to preprocess a source file
src/inet_onnx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/inet_onnx.cpp.i
.PHONY : src/inet_onnx.cpp.i

src/inet_onnx.s: src/inet_onnx.cpp.s
.PHONY : src/inet_onnx.s

# target to generate assembly for a file
src/inet_onnx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/inet_onnx.cpp.s
.PHONY : src/inet_onnx.cpp.s

src/json_log.o: src/json_log.cpp.o
.PHONY : src/json_log.o

# target to build an object file
src/json_log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/json_log.cpp.o
.PHONY : src/json_log.cpp.o

src/json_log.i: src/json_log.cpp.i
.PHONY : src/json_log.i

# target to preprocess a source file
src/json_log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/json_log.cpp.i
.PHONY : src/json_log.cpp.i

src/json_log.s: src/json_log.cpp.s
.PHONY : src/json_log.s

# target to generate assembly for a file
src/json_log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/json_log.cpp.s
.PHONY : src/json_log.cpp.s

src/logger.o: src/logger.cpp.o
.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/patch_graph.o: src/patch_graph.cpp.o
.PHONY : src/patch_graph.o

# target to build an object file
src/patch_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/patch_graph.cpp.o
.PHONY : src/patch_graph.cpp.o

src/patch_graph.i: src/patch_graph.cpp.i
.PHONY : src/patch_graph.i

# target to preprocess a source file
src/patch_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/patch_graph.cpp.i
.PHONY : src/patch_graph.cpp.i

src/patch_graph.s: src/patch_graph.cpp.s
.PHONY : src/patch_graph.s

# target to generate assembly for a file
src/patch_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/patch_graph.cpp.s
.PHONY : src/patch_graph.cpp.s

src/patchify.o: src/patchify.cpp.o
.PHONY : src/patchify.o

# target to build an object file
src/patchify.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/patchify.cpp.o
.PHONY : src/patchify.cpp.o

src/patchify.i: src/patchify.cpp.i
.PHONY : src/patchify.i

# target to preprocess a source file
src/patchify.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/patchify.cpp.i
.PHONY : src/patchify.cpp.i

src/patchify.s: src/patchify.cpp.s
.PHONY : src/patchify.s

# target to generate assembly for a file
src/patchify.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/patchify.cpp.s
.PHONY : src/patchify.cpp.s

src/point.o: src/point.cpp.o
.PHONY : src/point.o

# target to build an object file
src/point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/point.cpp.o
.PHONY : src/point.cpp.o

src/point.i: src/point.cpp.i
.PHONY : src/point.i

# target to preprocess a source file
src/point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/point.cpp.i
.PHONY : src/point.cpp.i

src/point.s: src/point.cpp.s
.PHONY : src/point.s

# target to generate assembly for a file
src/point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/point.cpp.s
.PHONY : src/point.cpp.s

src/projective_ops.o: src/projective_ops.cpp.o
.PHONY : src/projective_ops.o

# target to build an object file
src/projective_ops.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/projective_ops.cpp.o
.PHONY : src/projective_ops.cpp.o

src/projective_ops.i: src/projective_ops.cpp.i
.PHONY : src/projective_ops.i

# target to preprocess a source file
src/projective_ops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/projective_ops.cpp.i
.PHONY : src/projective_ops.cpp.i

src/projective_ops.s: src/projective_ops.cpp.s
.PHONY : src/projective_ops.s

# target to generate assembly for a file
src/projective_ops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/projective_ops.cpp.s
.PHONY : src/projective_ops.cpp.s

src/se3.o: src/se3.cpp.o
.PHONY : src/se3.o

# target to build an object file
src/se3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/se3.cpp.o
.PHONY : src/se3.cpp.o

src/se3.i: src/se3.cpp.i
.PHONY : src/se3.i

# target to preprocess a source file
src/se3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/se3.cpp.i
.PHONY : src/se3.cpp.i

src/se3.s: src/se3.cpp.s
.PHONY : src/se3.s

# target to generate assembly for a file
src/se3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/se3.cpp.s
.PHONY : src/se3.cpp.s

src/socket.o: src/socket.cpp.o
.PHONY : src/socket.o

# target to build an object file
src/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/socket.cpp.o
.PHONY : src/socket.cpp.o

src/socket.i: src/socket.cpp.i
.PHONY : src/socket.i

# target to preprocess a source file
src/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/socket.cpp.i
.PHONY : src/socket.cpp.i

src/socket.s: src/socket.cpp.s
.PHONY : src/socket.s

# target to generate assembly for a file
src/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/socket.cpp.s
.PHONY : src/socket.cpp.s

src/target_frame.o: src/target_frame.cpp.o
.PHONY : src/target_frame.o

# target to build an object file
src/target_frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/target_frame.cpp.o
.PHONY : src/target_frame.cpp.o

src/target_frame.i: src/target_frame.cpp.i
.PHONY : src/target_frame.i

# target to preprocess a source file
src/target_frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/target_frame.cpp.i
.PHONY : src/target_frame.cpp.i

src/target_frame.s: src/target_frame.cpp.s
.PHONY : src/target_frame.s

# target to generate assembly for a file
src/target_frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/target_frame.cpp.s
.PHONY : src/target_frame.cpp.s

src/update.o: src/update.cpp.o
.PHONY : src/update.o

# target to build an object file
src/update.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/update.cpp.o
.PHONY : src/update.cpp.o

src/update.i: src/update.cpp.i
.PHONY : src/update.i

# target to preprocess a source file
src/update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/update.cpp.i
.PHONY : src/update.cpp.i

src/update.s: src/update.cpp.s
.PHONY : src/update.s

# target to generate assembly for a file
src/update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/update.cpp.s
.PHONY : src/update.cpp.s

src/update_onnx.o: src/update_onnx.cpp.o
.PHONY : src/update_onnx.o

# target to build an object file
src/update_onnx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/update_onnx.cpp.o
.PHONY : src/update_onnx.cpp.o

src/update_onnx.i: src/update_onnx.cpp.i
.PHONY : src/update_onnx.i

# target to preprocess a source file
src/update_onnx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/update_onnx.cpp.i
.PHONY : src/update_onnx.cpp.i

src/update_onnx.s: src/update_onnx.cpp.s
.PHONY : src/update_onnx.s

# target to generate assembly for a file
src/update_onnx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/update_onnx.cpp.s
.PHONY : src/update_onnx.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/yolov8.o: src/yolov8.cpp.o
.PHONY : src/yolov8.o

# target to build an object file
src/yolov8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8.cpp.o
.PHONY : src/yolov8.cpp.o

src/yolov8.i: src/yolov8.cpp.i
.PHONY : src/yolov8.i

# target to preprocess a source file
src/yolov8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8.cpp.i
.PHONY : src/yolov8.cpp.i

src/yolov8.s: src/yolov8.cpp.s
.PHONY : src/yolov8.s

# target to generate assembly for a file
src/yolov8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8.cpp.s
.PHONY : src/yolov8.cpp.s

src/yolov8_decoder.o: src/yolov8_decoder.cpp.o
.PHONY : src/yolov8_decoder.o

# target to build an object file
src/yolov8_decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8_decoder.cpp.o
.PHONY : src/yolov8_decoder.cpp.o

src/yolov8_decoder.i: src/yolov8_decoder.cpp.i
.PHONY : src/yolov8_decoder.i

# target to preprocess a source file
src/yolov8_decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8_decoder.cpp.i
.PHONY : src/yolov8_decoder.cpp.i

src/yolov8_decoder.s: src/yolov8_decoder.cpp.s
.PHONY : src/yolov8_decoder.s

# target to generate assembly for a file
src/yolov8_decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8_decoder.cpp.s
.PHONY : src/yolov8_decoder.cpp.s

src/yolov8_onnx.o: src/yolov8_onnx.cpp.o
.PHONY : src/yolov8_onnx.o

# target to build an object file
src/yolov8_onnx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8_onnx.cpp.o
.PHONY : src/yolov8_onnx.cpp.o

src/yolov8_onnx.i: src/yolov8_onnx.cpp.i
.PHONY : src/yolov8_onnx.i

# target to preprocess a source file
src/yolov8_onnx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8_onnx.cpp.i
.PHONY : src/yolov8_onnx.cpp.i

src/yolov8_onnx.s: src/yolov8_onnx.cpp.s
.PHONY : src/yolov8_onnx.s

# target to generate assembly for a file
src/yolov8_onnx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wnc-app.dir/build.make CMakeFiles/wnc-app.dir/src/yolov8_onnx.cpp.s
.PHONY : src/yolov8_onnx.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... wnc-app"
	@echo "... src/ba.o"
	@echo "... src/ba.i"
	@echo "... src/ba.s"
	@echo "... src/bounding_box.o"
	@echo "... src/bounding_box.i"
	@echo "... src/bounding_box.s"
	@echo "... src/config_reader.o"
	@echo "... src/config_reader.i"
	@echo "... src/config_reader.s"
	@echo "... src/correlation_kernel.o"
	@echo "... src/correlation_kernel.i"
	@echo "... src/correlation_kernel.s"
	@echo "... src/dla_config.o"
	@echo "... src/dla_config.i"
	@echo "... src/dla_config.s"
	@echo "... src/dpvo.o"
	@echo "... src/dpvo.i"
	@echo "... src/dpvo.s"
	@echo "... src/dpvo_viewer.o"
	@echo "... src/dpvo_viewer.i"
	@echo "... src/dpvo_viewer.s"
	@echo "... src/fnet.o"
	@echo "... src/fnet.i"
	@echo "... src/fnet.s"
	@echo "... src/fnet_onnx.o"
	@echo "... src/fnet_onnx.i"
	@echo "... src/fnet_onnx.s"
	@echo "... src/img_util.o"
	@echo "... src/img_util.i"
	@echo "... src/img_util.s"
	@echo "... src/inet.o"
	@echo "... src/inet.i"
	@echo "... src/inet.s"
	@echo "... src/inet_onnx.o"
	@echo "... src/inet_onnx.i"
	@echo "... src/inet_onnx.s"
	@echo "... src/json_log.o"
	@echo "... src/json_log.i"
	@echo "... src/json_log.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/patch_graph.o"
	@echo "... src/patch_graph.i"
	@echo "... src/patch_graph.s"
	@echo "... src/patchify.o"
	@echo "... src/patchify.i"
	@echo "... src/patchify.s"
	@echo "... src/point.o"
	@echo "... src/point.i"
	@echo "... src/point.s"
	@echo "... src/projective_ops.o"
	@echo "... src/projective_ops.i"
	@echo "... src/projective_ops.s"
	@echo "... src/se3.o"
	@echo "... src/se3.i"
	@echo "... src/se3.s"
	@echo "... src/socket.o"
	@echo "... src/socket.i"
	@echo "... src/socket.s"
	@echo "... src/target_frame.o"
	@echo "... src/target_frame.i"
	@echo "... src/target_frame.s"
	@echo "... src/update.o"
	@echo "... src/update.i"
	@echo "... src/update.s"
	@echo "... src/update_onnx.o"
	@echo "... src/update_onnx.i"
	@echo "... src/update_onnx.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/yolov8.o"
	@echo "... src/yolov8.i"
	@echo "... src/yolov8.s"
	@echo "... src/yolov8_decoder.o"
	@echo "... src/yolov8_decoder.i"
	@echo "... src/yolov8_decoder.s"
	@echo "... src/yolov8_onnx.o"
	@echo "... src/yolov8_onnx.i"
	@echo "... src/yolov8_onnx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

